#PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5433/maathacare_db
spring.datasource.username=postgres
spring.datasource.password=kodisenu04
server.address=0.0.0.0

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


